#import "IGLInsNotificationSet.h"
@implementation IGLInsNotificationSet
NSNotificationName const IGLInsFBLoginCancelNotification_Login = @"InsFBLoginCancelNotification";
NSNotificationName const IGLInsFBLoginSuccessNotification_Login = @"InsFBLoginSuccessNotification";
NSNotificationName const IGLInsFBLoginGetUserInfoSuccessNotification_Login = @"InsFBLoginGetUserInfoSuccessNotification";
NSNotificationName const IGLInsFBLoginGetUserInfoFailedNotification_Login = @"InsFBLoginGetUserInfoFailedNotification";
@end
